// cmd/omega/webkit/nuxt/app/pages/login.vue
<script setup lang="ts">
import { EyeIcon, EyeOffIcon } from 'lucide-vue-next'
import { ApiError } from '~/lib/api'

definePageMeta({ layout: 'default' })

const { t } = useI18n()
const { signIn, signUp } = useAuth()
const toast = useToast()

const tab = ref('signin')
const pending = ref(false)
const fields = ref<Record<string, string>>({})
const revealed = ref(false)

const form = reactive({ name: '', email: 'admin@omega.test', password: '' })

async function run(action: () => Promise<void>) {
  pending.value = true
  fields.value = {}
  try {
    await action()
    await navigateTo('/dashboard')
  }
  catch (error) {
    if (error instanceof ApiError) {
      fields.value = error.fields ?? {}
      toast.error(error.message)
    }
    else {
      toast.error(t('auth.unreachable'))
    }
  }
  finally {
    pending.value = false
  }
}
</script>

<template>
  <div class="flex min-h-svh items-center justify-center p-4">
    <UiCard class="w-full max-w-md" :title="t('auth.title')">
      <UiTabs
        v-model="tab"
        :tabs="[{ value: 'signin', label: t('auth.signIn') }, { value: 'signup', label: t('auth.signUp') }]"
      >
        <form class="flex flex-col gap-4" @submit.prevent="run(() => tab === 'signin'
          ? signIn(form.email, form.password)
          : signUp(form.name, form.email, form.password))"
        >
          <UiField v-if="tab === 'signup'" :label="t('auth.name')" for="name" :error="fields.name">
            <UiInput id="name" v-model="form.name" :placeholder="t('auth.namePlaceholder')" autocomplete="name" :invalid="!!fields.name" />
          </UiField>

          <UiField :label="t('auth.email')" for="email" :error="fields.email">
            <UiInput id="email" v-model="form.email" type="email" :placeholder="t('auth.emailPlaceholder')" autocomplete="email" :invalid="!!fields.email" />
          </UiField>

          <UiField :label="t('auth.password')" for="password" :error="fields.password">
            <div class="relative">
              <UiInput
                id="password"
                v-model="form.password"
                :type="revealed ? 'text' : 'password'"
                :placeholder="t('auth.passwordPlaceholder')"
                :autocomplete="tab === 'signin' ? 'current-password' : 'new-password'"
                :invalid="!!fields.password"
                class="pr-9"
              />
              <UiButton
                variant="ghost"
                size="icon-sm"
                type="button"
                tabindex="-1"
                class="absolute inset-y-0 right-1 my-auto text-ink-gray-5"
                :aria-pressed="revealed"
                :aria-label="revealed ? t('auth.hidePassword') : t('auth.showPassword')"
                @click="revealed = !revealed"
              >
                <EyeOffIcon v-if="revealed" />
                <EyeIcon v-else />
              </UiButton>
            </div>
          </UiField>

          <UiButton type="submit" :disabled="pending" class="w-full">
            <UiSpinner v-if="pending" />
            {{ tab === 'signin'
              ? (pending ? t('auth.signingIn') : t('auth.signIn'))
              : (pending ? t('auth.creating') : t('auth.signUp')) }}
          </UiButton>
        </form>
      </UiTabs>
    </UiCard>
  </div>
</template>

// cmd/omega/webkit/next/app/(site)/login/page.tsx
"use client"

import { useState } from "react"
import { EyeIcon, EyeOffIcon } from "lucide-react"
import { useTranslation } from "@/lib/i18n"
import { useRouter } from "next/navigation"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ApiError } from "@/lib/api"
import { useAuth } from "@/lib/auth"
import { notifyError, notifySuccess } from "@/lib/notify"

export default function LoginPage() {
  const { signIn, signUp } = useAuth()
  const router = useRouter()

  const { t } = useTranslation()
  const [pending, setPending] = useState(false)
  const [fields, setFields] = useState<Record<string, string>>({})

  async function run(action: () => Promise<void>, success: string) {
    setPending(true)
    setFields({})
    try {
      await action()
      notifySuccess(t(success))
      void router.push("/dashboard")
    } catch (failure) {
      if (failure instanceof ApiError && failure.fields) setFields(failure.fields)
      notifyError(failure)
    } finally {
      setPending(false)
    }
  }

  return (
    <div className="flex min-h-svh items-center justify-center bg-muted/30 p-6">
      <title>{`${t("auth.signIn")} · Omega`}</title>
      <Card className="w-full max-w-sm">
        <CardHeader>
          <div className="mb-2 flex size-10 items-center justify-center rounded-lg bg-primary text-lg font-bold text-primary-foreground">
            Ω
          </div>
          <CardTitle>Omega</CardTitle>
          <CardDescription>{t("auth.title")}</CardDescription>
        </CardHeader>

        <CardContent>
          <Tabs defaultValue="signin" onValueChange={() => setFields({})}>
            <TabsList className="mb-4 w-full">
              <TabsTrigger value="signin" className="flex-1">{t("auth.signIn")}</TabsTrigger>
              <TabsTrigger value="signup" className="flex-1">{t("auth.signUp")}</TabsTrigger>
            </TabsList>

            <TabsContent value="signin">
              <form
                onSubmit={(event) => {
                  event.preventDefault()
                  const form = new FormData(event.currentTarget)
                  void run(
                    () => signIn(String(form.get("email")), String(form.get("password"))),
                    "errors.signedIn",
                  )
                }}
              >
                <FieldGroup className="gap-4">
                  <TextField
                    name="email"
                    label={t("auth.email")}
                    type="email"
                    placeholder={t("auth.emailPlaceholder")}
                    autoComplete="email"
                    error={fields.email}
                    defaultValue="admin@omega.test"
                  />
                  <TextField
                    name="password"
                    label={t("auth.password")}
                    type="password"
                    placeholder={t("auth.passwordPlaceholder")}
                    autoComplete="current-password"
                    error={fields.password}
                  />
                  <Button type="submit" disabled={pending} className="w-full">
                    {pending && <Spinner />}
                    {pending ? t("auth.signingIn") : t("auth.signIn")}
                  </Button>
                </FieldGroup>
              </form>
            </TabsContent>

            <TabsContent value="signup">
              <form
                onSubmit={(event) => {
                  event.preventDefault()
                  const form = new FormData(event.currentTarget)
                  void run(
                    () =>
                      signUp(
                        String(form.get("name")),
                        String(form.get("email")),
                        String(form.get("password")),
                      ),
                    "errors.accountCreated",
                  )
                }}
              >
                <FieldGroup className="gap-4">
                  <TextField
                    name="name"
                    label={t("auth.name")}
                    placeholder={t("auth.namePlaceholder")}
                    autoComplete="name"
                    error={fields.name}
                  />
                  <TextField
                    name="email"
                    label={t("auth.email")}
                    type="email"
                    placeholder={t("auth.emailPlaceholder")}
                    autoComplete="email"
                    error={fields.email}
                  />
                  <TextField
                    name="password"
                    label={t("auth.password")}
                    type="password"
                    placeholder={t("auth.passwordPlaceholder")}
                    autoComplete="new-password"
                    error={fields.password}
                  />
                  <Button type="submit" disabled={pending} className="w-full">
                    {pending && <Spinner />}
                    {pending ? t("auth.creating") : t("auth.signUp")}
                  </Button>
                </FieldGroup>
              </form>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}

function TextField({
  name,
  label,
  type = "text",
  autoComplete,
  error,
  defaultValue,
  placeholder,
}: {
  name: string
  label: string
  type?: string
  autoComplete?: string
  error?: string
  defaultValue?: string
  placeholder?: string
}) {
  const { t } = useTranslation()
  const [revealed, setRevealed] = useState(false)
  const isPassword = type === "password"

  return (
    <Field data-invalid={Boolean(error)}>
      <FieldLabel htmlFor={name}>{label}</FieldLabel>
      <div className="relative">
        <Input
          id={name}
          name={name}
          type={isPassword && revealed ? "text" : type}
          defaultValue={defaultValue}
          placeholder={placeholder}
          autoComplete={autoComplete}
          aria-invalid={Boolean(error)}
          className={isPassword ? "pr-9" : undefined}
        />
        {isPassword && (
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            tabIndex={-1}
            aria-pressed={revealed}
            aria-label={revealed ? t("auth.hidePassword") : t("auth.showPassword")}
            onClick={() => setRevealed((shown) => !shown)}
            className="absolute inset-y-0 right-1 my-auto text-ink-gray-5"
          >
            {revealed ? <EyeOffIcon /> : <EyeIcon />}
          </Button>
        )}
      </div>
      <FieldError>{error}</FieldError>
    </Field>
  )
}
