// cmd/omega/webkit/nuxt/app/pages/dashboard.vue
<script setup lang="ts">
import { BadgeCheckIcon, ShieldCheckIcon, UsersIcon } from 'lucide-vue-next'
import { api } from '~/lib/api'

definePageMeta({ layout: 'dashboard', middleware: 'auth' })

const { t } = useI18n()

const { data: all, pending } = await useAsyncData('stats', () => api.users({ per_page: 200 }))
const { data: recent } = await useAsyncData('recent', () => api.users({ per_page: 5, sort: '-created_at' }))

const users = computed(() => all.value?.data ?? [])
const total = computed(() => all.value?.meta.total ?? 0)

const cards = computed(() => {
  const admins = users.value.filter(user => user.role === 'admin').length
  const verified = users.value.filter(user => user.email_verified_at).length

  return [
    { key: 'totalUsers', value: total.value, icon: UsersIcon, ratio: 100 },
    { key: 'admins', value: admins, icon: ShieldCheckIcon, ratio: total.value ? (admins / total.value) * 100 : 0 },
    { key: 'verified', value: verified, icon: BadgeCheckIcon, ratio: total.value ? (verified / total.value) * 100 : 0 },
  ]
})
</script>

<template>
  <div class="flex flex-col gap-6">
    <div class="grid gap-4 sm:grid-cols-3">
      <UiCard v-for="card in cards" :key="card.key">
        <template #header>
          <div class="flex items-center justify-between">
            <p class="text-p-sm text-ink-gray-5">
              {{ t(`dashboard.${card.key}`) }}
            </p>
            <component :is="card.icon" class="size-4 text-ink-gray-5" />
          </div>
        </template>

        <div class="grid gap-3">
          <UiSkeleton v-if="pending" class="h-8 w-16" />
          <span v-else class="text-4xl font-semibold tabular text-ink-gray-9">{{ card.value }}</span>
          <UiProgress :value="card.ratio" />
        </div>
      </UiCard>
    </div>

    <UiCard :title="t('dashboard.recent')">
      <div v-if="pending" class="flex flex-col gap-3">
        <UiSkeleton v-for="index in 3" :key="index" class="h-10 w-full" />
      </div>

      <p v-else-if="!recent?.data.length" class="py-8 text-center text-base text-ink-gray-5">
        {{ t('dashboard.empty') }}
      </p>

      <ul v-else class="divide-y divide-outline-gray-1">
        <li v-for="user in recent.data" :key="user.id" class="flex items-center gap-3 py-2.5">
          <UiAvatar :name="user.name" />
          <div class="min-w-0 flex-1">
            <NuxtLink :to="`/users/${user.id}`" class="block truncate text-base font-medium text-ink-gray-9 hover:underline">
              {{ user.name }}
            </NuxtLink>
            <p class="truncate text-sm text-ink-gray-5">
              {{ user.email }}
            </p>
          </div>
          <UiBadge :variant="user.role === 'admin' ? 'brand' : 'default'">
            {{ user.role }}
          </UiBadge>
        </li>
      </ul>
    </UiCard>
  </div>
</template>

// cmd/omega/webkit/react/src/pages/dashboard.tsx
import { useQuery } from "@/lib/query"
import { BadgeCheck, ShieldCheck, Users } from "lucide-react"
import { useTranslation } from "@/lib/i18n"
import { Link } from "react-router"

import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty"
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemGroup,
  ItemMedia,
  ItemTitle,
} from "@/components/ui/item"
import { Progress } from "@/components/ui/progress"
import { Skeleton } from "@/components/ui/skeleton"
import { api } from "@/lib/api"

export function DashboardPage() {
  const { t } = useTranslation()

  const all = useQuery({ queryKey: ["stats"], queryFn: () => api.users({ per_page: 200 }) })
  const recent = useQuery({
    queryKey: ["recent"],
    queryFn: () => api.users({ per_page: 5, sort: "-created_at" }),
  })

  const users = all.data?.data ?? []
  const total = all.data?.meta.total ?? 0
  const admins = users.filter((user) => user.role === "admin").length
  const verified = users.filter((user) => user.email_verified_at).length

  const cards = [
    { key: "totalUsers", value: total, icon: Users, ratio: 100 },
    { key: "admins", value: admins, icon: ShieldCheck, ratio: total ? (admins / total) * 100 : 0 },
    { key: "verified", value: verified, icon: BadgeCheck, ratio: total ? (verified / total) * 100 : 0 },
  ]

  return (
    <div className="flex flex-col gap-6">
      <div className="grid gap-4 sm:grid-cols-3">
        {cards.map((card) => (
          <Card key={card.key}>
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardDescription>{t(`dashboard.${card.key}`)}</CardDescription>
              <card.icon className="size-4 text-muted-foreground" />
            </CardHeader>
            <CardContent className="grid gap-3">
              {all.isPending ? (
                <Skeleton className="h-8 w-16" />
              ) : (
                <span className="text-3xl font-semibold tabular-nums">{card.value}</span>
              )}
              <Progress value={card.ratio} className="h-1.5" />
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">{t("dashboard.recent")}</CardTitle>
          <CardDescription>
            <code className="text-xs">GET /api/users?sort=-created_at&per_page=5</code>
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ItemGroup>
            {recent.isPending &&
              Array.from({ length: 5 }, (_, index) => (
                <Skeleton key={index} className="h-14 w-full" />
              ))}

            {recent.data?.data.map((user) => (
              <Item key={user.id} asChild>
                <Link to={`/users/${user.id}`}>
                  <ItemMedia>
                    <Avatar className="size-9">
                      <AvatarFallback className="text-xs">
                        {user.name?.slice(0, 2).toUpperCase()}
                      </AvatarFallback>
                    </Avatar>
                  </ItemMedia>
                  <ItemContent>
                    <ItemTitle>{user.name}</ItemTitle>
                    <ItemDescription>{user.email}</ItemDescription>
                  </ItemContent>
                  <ItemActions>
                    <Badge variant={user.role === "admin" ? "default" : "secondary"}>
                      {user.role}
                    </Badge>
                  </ItemActions>
                </Link>
              </Item>
            ))}

            {recent.data?.data.length === 0 && (
              <Empty>
                <EmptyHeader>
                  <EmptyMedia variant="icon">
                    <Users />
                  </EmptyMedia>
                  <EmptyTitle>{t("users.empty")}</EmptyTitle>
                </EmptyHeader>
              </Empty>
            )}
          </ItemGroup>
        </CardContent>
      </Card>
    </div>
  )
}
